### ISSUE TITLE
Pro controllers support

### ISSUE THREAD

**Issue by fgsfds** [ROFISH/FC30XInput#1]
Any chance you can add support for Pro controllers?

**Comment by pjpalomaki** [comment]
And SNES30 please.

Also, not sure if the issue is that I'm using SNES30 controller, but when I start the Xinput emulation, I get the following error and crash following:

![sfc30xinput](https://cloud.githubusercontent.com/assets/9024380/15269872/b4dc15f8-1a04-11e6-9545-0007435689ab.PNG)

I'm on Win 10 64Bit.

**Comment by slaucsap** [comment]
@pjpalomaki I know its a little late but I had your same issue (on windows 7, SFC30 controller) I think I fixed it using this:
http://download.8bitdo.com/Driver/Virtual_Bus_Driver.zip


As a side note if the creator is seeing this I'd like to add: 

Thanks.


and also it would be cool another option like the "D-pad on controller corresponds to:" for the L and R buttons, so we can choose if those correspond to LT/RT or LB/RB
